config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get 'home/about'
  get 'home/contact'
  get 'home/faq'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end

    def correct_user
      @pin  = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Nie jesteś uprawiony do edycji  tego pinu" if @pin.nil?

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Obrazkowo', root_path, class:"navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Strona główna", root_path %></li>
      <li><%= link_to "O mnie", home_about_path %></li>
      <li><%= link_to "Lista pinów", pins_path %></li>

      <% if user_signed_in? %>
          <li><%= link_to "Edycja Profilu", edit_user_registration_path %></li>
          <li><%= link_to "Nowy Pin", new_pin_path %></li>
          <li><%= link_to "Wylogowanie", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Logowanie", new_user_session_path %></li>
          <li><%= link_to "Rejestracja", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>O mnie</h1>
<p>Rails oparte jest o architekturę MVC, tzn. klient po wyświetleniu widoku (w tym przypadku wygenerowanej strony HTML), wysyła do aplikacji żądanie (klikając w odpowiedni link na stronie lub wypełniając formularz). Żądanie jest przyjmowane przez kontroler, który generuje odpowiedź w formie widoku wysyłanego do klienta (najczęściej kontroler w celu wygenerowania odpowiedzi pobiera dane z modelu, który w Rails implementowany jest jako relacyjna baza danych). Poniżej szczegółowo omówiono mechanizmy odpowiedzialne w Rails za model MVC.</p>

app/views/home/contact.html.erb
<h1>Contact</h1>

app/views/home/faq.html.erb
<h1>Faq</h1>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>Witaj w aplikacji</h1>
<p>Find me in app/views/home/index.html.erb</p>
  <%= link_to 'O mnie', home_about_path, class: "btn btn-primary btn-lg" %>
  <%= link_to 'Strona główna', root_path, class: "btn btn-info btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Obrazkowo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name ="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <body>

    <%= render 'home/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pins/_form.html.erb
<!-- <%= form_with(model: pin, local: true) do |form| %> -->
<%= form_for @pin, html: {multipart: true} do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %><br />
    <%= form.text_field :description, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :image, "Obraz" %>
    <%= form.file_field :image, class:"form-control" %>
  </div>


  <div class="actions">
    <%= form.submit "Create a new pin", class: 'btn btn-primary' %>
  </div>

<% end %>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<% if user_signed_in? %>
  <div class="jumbotron">
    <h1>Witaj w aplikacji</h1>
    <p>Find me in app/views/home/index.html.erb</p>
      <%= link_to 'O mnie', home_about_path, class: "btn btn-primary btn-lg" %>
      <%= link_to 'Strona główna', root_path, class: "btn btn-info btn-lg" %>
  </div>
<% end %>


<div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
    <div class="box">
      <div class="panel panel-dfault">
        <%= link_to image_tag(pin.image.url(:medium)), pin %><br/>
        <div class="panel-body">
        <%= pin.description %><br/>
        </div>
          <% if pin.user == current_user %>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_pin_path(pin) %><br/>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="center">
        <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
  </div>

app/views/pins/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h1>New Pin</h1></div>
<div class="panel-body">

<%= render 'form', pin: @pin %><br />

<div class="panel-footer"><%= link_to 'Back', pins_path %></div>
</div>
</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center"><%= image_tag @pin.image.url(:medium) %></div>
    <div class="panel-body">
        <%= @pin.description %><br/>
          <% if @pin.user == current_user %>
            <%= link_to 'Edit', edit_pin_path(@pin) %> |
          <% end %>
        <%= link_to 'Back', pins_path %>
      </div>
    </div>
  </div>
</div>